project:
  type: website

website:
  title: "mi-blog"
  navbar:
    # background: "#eae9dd" 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    left: 
      - text: "Adán González González"
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    highlight-style: zenburn

editor: visual

# Change the background to a different color.
# Add another hyperlink in the navigation bar.
# Add your name to the left side of the top navigation bar.

# Change to another Bootswatch theme.
# Add a dark theme with another Bootswatch theme.
# Change the syntax highlighting to `eiffel`.

