project:
  type: website

website:
  title: "build-your-own-blog-exercises"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

# Change the background to a different color.
# Add another hyperlink in the navigation bar.
# Add your name to the left side of the top navigation bar.

# Change to another Bootswatch theme.
# Add a dark theme with another Bootswatch theme.
# Change the syntax highlighting to `eiffel`.

